// <auto-generated />
using Abby.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Abby.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250322141826_MenuFull")]
    partial class MenuFull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Abby.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Vorspeisen"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Hauptgerichte"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Getränke"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Vegane Speisen"
                        });
                });

            modelBuilder.Entity("Abby.Models.FoodType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vegetarisch"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fleisch"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fisch"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vegan"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Glutenfrei"
                        });
                });

            modelBuilder.Entity("Abby.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FoodTypeId");

                    b.ToTable("MenuItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Frischer Römersalat mit Parmesan & Croutons",
                            FoodTypeId = 1,
                            Image = "https://example.com/salad.jpg",
                            Name = "Caesar Salad",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Klassische italienische Pasta mit Speck & Ei",
                            FoodTypeId = 2,
                            Image = "https://example.com/carbonara.jpg",
                            Name = "Spaghetti Carbonara",
                            Price = 12.99
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Gegrillter Lachs mit Zitronenbutter & Gemüse",
                            FoodTypeId = 3,
                            Image = "https://example.com/salmon.jpg",
                            Name = "Lachsfilet",
                            Price = 18.5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Saftiger Schokokuchen mit warmer Schokosauce",
                            FoodTypeId = 1,
                            Image = "https://example.com/chocolatecake.jpg",
                            Name = "Schokoladenkuchen",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Frischer Smoothie mit Mango & Banane",
                            FoodTypeId = 4,
                            Image = "https://example.com/mango_smoothie.jpg",
                            Name = "Mango Smoothie",
                            Price = 4.5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Description = "Hausgemachte Falafel mit Hummus & Gemüse",
                            FoodTypeId = 4,
                            Image = "https://example.com/falafel.jpg",
                            Name = "Falafel Wrap",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Saftiges Steak mit Rosmarinkartoffeln",
                            FoodTypeId = 2,
                            Image = "https://example.com/steak.jpg",
                            Name = "Steak Medium-Rare",
                            Price = 24.989999999999998
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Klassisches italienisches Dessert mit Mascarpone",
                            FoodTypeId = 1,
                            Image = "https://example.com/tiramisu.jpg",
                            Name = "Tiramisu",
                            Price = 7.5
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Wärmende Linsensuppe mit orientalischen Gewürzen",
                            FoodTypeId = 5,
                            Image = "https://example.com/lentilsoup.jpg",
                            Name = "Linsensuppe",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Gesunde Bowl mit Quinoa, Kichererbsen & Avocado",
                            FoodTypeId = 4,
                            Image = "https://example.com/buddhabowl.jpg",
                            Name = "Vegane Buddha Bowl",
                            Price = 10.99
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Klassische italienische Pizza mit Mozzarella & Basilikum",
                            FoodTypeId = 1,
                            Image = "https://example.com/images/margherita_pizza.jpg",
                            Name = "Margherita Pizza",
                            Price = 9.9900000000000002
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Verschiedene Sushi-Rollen mit Wasabi & Sojasauce",
                            FoodTypeId = 3,
                            Image = "https://example.com/images/sushi_mix.jpg",
                            Name = "Sushi Mix",
                            Price = 14.99
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Saftiger Hähnchenburger mit Salat & Mayo",
                            FoodTypeId = 2,
                            Image = "https://example.com/images/chicken_burger.jpg",
                            Name = "Chicken Burger",
                            Price = 11.5
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            Description = "Leichte Suppe mit frischem Gemüse",
                            FoodTypeId = 5,
                            Image = "https://example.com/images/gemuesesuppe.jpg",
                            Name = "Gemüsesuppe",
                            Price = 6.5
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            Description = "Fruchtiger Smoothie mit Erdbeeren & Joghurt",
                            FoodTypeId = 4,
                            Image = "https://example.com/images/erdbeer_smoothie.jpg",
                            Name = "Erdbeer-Smoothie",
                            Price = 4.9900000000000002
                        });
                });

            modelBuilder.Entity("Abby.Models.MenuItem", b =>
                {
                    b.HasOne("Abby.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Abby.Models.FoodType", "FoodType")
                        .WithMany()
                        .HasForeignKey("FoodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FoodType");
                });
#pragma warning restore 612, 618
        }
    }
}
